extern void scroll_castle_courtyard_dl_Circle_005_mesh_layer_5_vtx_0();
extern void scroll_sts_mat_castle_courtyard_dl_Clouds_001();
extern void scroll_castle_courtyard_dl_Plane_002_mesh_layer_5_vtx_0();
extern void scroll_sts_mat_castle_courtyard_dl_water2();
extern void scroll_castle_courtyard_dl_Plane_009_mesh_layer_5_vtx_0();
extern void scroll_sts_mat_castle_courtyard_dl_WF_001();
extern void scroll_castle_courtyard();
